import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <header className="bg-blue-600 text-white p-4">
          <h1 className="text-2xl">Inventory Management</h1>
        </header>
        <main className="flex-grow p-4">{children}</main>
        <footer className="bg-blue-600 text-white text-center py-4 mt-auto">
          &copy; 2024 My Inventory System
        </footer>
      </body>
    </html>
  );
}
